# https://taskfile.dev
version: '3'
vars:
  IMG: sgaunet/gitlab-backup2s3:latest
  BINFILE: gitlab-backup2s3

includes:
  dev: ./Taskfile_dev.yml

tasks:
  default:
    desc: "List tasks"
    cmds:
      - task -a

  linter:
    desc: "Run linter"
    cmds:
      - golangci-lint run --timeout 5m

  binary:
    desc: "Build binary"
    cmds:
      - CGO_ENABLED=0 go build .

  image:
    desc: "Build/push docker image"
    deps: 
    - binary
    cmds:
      - docker build . -t {{.IMG}}
      - docker push {{.IMG}}

  snapshot:
    desc: "Create a snapshot release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean --snapshot

  release:
    desc: "Create a release"
    cmds:
      - GITLAB_TOKEN="" goreleaser --clean
